version: '3.8'
services:
    pgsql:
        image: postgres:14.1-alpine
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DATABASE_SUPERUSER_NAME}
            - POSTGRES_PASSWORD=${DATABASE_SUPERUSER_PASSWORD}
            - TZ=${DATABASE_TIMEZONE}
            - PGTZ=${DATABASE_TIMEZONE}
            - PGDATESTYLE=${DATABASE_DATE_STYLE}
        ports:
            - ${DATABASE_PORT}:5432
        volumes:
            - ./tmp/pgsql:/var/lib/postgresql/data
            - ./docker/pgsql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
    pgsql:
        driver: local
