#!/usr/bin/env bash
set -e

echo "creating users and databases..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_SUPERUSER_NAME" <<-EOSQL
	CREATE USER "$POSTGRES_USER_NAME" WITH ENCRYPTED PASSWORD '$POSTGRES_USER_PASSWORD';
	CREATE DATABASE "$POSTGRES_DB_NAME" WITH OWNER "$POSTGRES_USER_NAME" ENCODING 'UTF8';
EOSQL
