#!/usr/bin/env bash
set -e

echo "creating users and databases..."
psql -v ON_ERROR_STOP=1 --username "$DATABASE_SUPERUSER_NAME" <<-EOSQL
	CREATE USER "$DATABASE_USER_NAME" WITH ENCRYPTED PASSWORD '$DATABASE_USER_PASSWORD';
	CREATE DATABASE "$DATABASE_NAME" WITH OWNER "$DATABASE_USER_NAME" ENCODING 'UTF8';
EOSQL
